### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ylafont** [virantha/scanpdf#1]
I am missing something that is not obviuos to,  i just keep getting errors.

pi@PiScanner ~ $ sudo scanpdf scan pdf test.pdf
{'--blank-threshold': '0.97',
 '--debug': False,
 '--dpi': '300',
 '--face-up': 'True',
 '--keep-blanks': False,
 '--post-process': False,
 '--tmpdir': None,
 '--verbose': False,
 '<pdffile>': None,
 '<pdfile>': 'test.pdf',
 'pdf': True,
 'scan': True}
Traceback (most recent call last):
  File "/usr/local/bin/scanpdf", line 9, in <module>
    load_entry_point('scanpdf==0.3.0', 'console_scripts', 'scanpdf')()
  File "/usr/local/lib/python2.7/dist-packages/scanpdf/scanpdf.py", line 401, in main
    script.go(args)
  File "/usr/local/lib/python2.7/dist-packages/scanpdf/scanpdf.py", line 356, in go
    self.get_options(argv)
  File "/usr/local/lib/python2.7/dist-packages/scanpdf/scanpdf.py", line 320, in get_options
    self.pdf_filename = os.path.abspath(self.args['<pdffile>'])
  File "/usr/lib/python2.7/posixpath.py", line 352, in abspath
    if not isabs(path):
  File "/usr/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by kvdb** [comment]
Changing the following line in scanpdf.py from:

            self.pdf_filename = os.path.abspath(self.args['<pdffile>'])
into:

            self.pdf_filename = os.path.abspath(self.args['<pdfile>'])

At least makes it fetch the right docopt parameter name.

**Comment by virantha** [comment]
Thanks, missed that! (I really need to add some tests)  Fixed on master and PyPi 0.3.1
